createOrReplace

	table dim_calendario
		lineageTag: 3add6b18-ab4a-4839-934c-d03d99bff0e1

		column Data
			dataType: dateTime
			formatString: Short Date
			lineageTag: 437a94be-5d21-4c83-a222-46a8d8ad4c9a
			summarizeBy: none
			sourceColumn: Data
			sortByColumn: 'Nome Mês'

			variation Variation
				isDefault
				relationship: 2f839008-7634-4412-82cb-31dc6a489246
				defaultHierarchy: LocalDateTable_bea7b7cd-4e5a-4991-89e3-817011c4209d.'Hierarquia de datas'

			changedProperty = SortByColumn

			annotation SummarizationSetBy = Automatic

			annotation UnderlyingDateTimeDataType = Date

		column Ano
			dataType: int64
			formatString: 0
			lineageTag: e3cb0404-86f8-4c35-a2d9-c2fa7c982aef
			summarizeBy: sum
			sourceColumn: Ano

			annotation SummarizationSetBy = Automatic

		column Mês
			dataType: int64
			formatString: 0
			lineageTag: 8c3d9322-f074-4395-88cc-cf39b0ff7769
			summarizeBy: sum
			sourceColumn: Mês

			annotation SummarizationSetBy = Automatic

		column 'Nome Mês'
			dataType: string
			lineageTag: 91c1ed14-c941-4436-9074-a9826578408d
			summarizeBy: none
			sourceColumn: Nome Mês

			annotation SummarizationSetBy = Automatic

		column Dia
			dataType: int64
			formatString: 0
			lineageTag: 1f3be0ee-0a77-4137-bc07-9838059d3799
			summarizeBy: sum
			sourceColumn: Dia

			annotation SummarizationSetBy = Automatic

		column 'Dia Semana'
			dataType: int64
			formatString: 0
			lineageTag: 56da6752-d717-4cb7-bb79-51e8daf10edb
			summarizeBy: sum
			sourceColumn: Dia Semana

			annotation SummarizationSetBy = Automatic

		column 'Nome Dia Semana'
			dataType: string
			lineageTag: c8a5bf03-5875-4e89-bdcf-5407e2fee455
			summarizeBy: none
			sourceColumn: Nome Dia Semana

			annotation SummarizationSetBy = Automatic

		column Ano-Mês
			dataType: string
			lineageTag: d92fc036-c127-48f5-9985-ba1d3f923f51
			summarizeBy: none
			sourceColumn: Ano-Mês

			annotation SummarizationSetBy = Automatic

		column 'Início do Mês'
			dataType: dateTime
			formatString: Short Date
			lineageTag: af4d3a6b-d014-4940-a49a-24d8a61f70c0
			summarizeBy: none
			sourceColumn: Início do Mês

			variation Variation
				isDefault
				relationship: 46152887-c1fe-4ccb-8afa-ed1756e1958c
				defaultHierarchy: LocalDateTable_498158f6-430a-4bd6-80e9-7622cf64ec13.'Hierarquia de datas'

			annotation SummarizationSetBy = Automatic

			annotation UnderlyingDateTimeDataType = Date

		partition dim_calendario = m
			mode: import
			source =
					let
					    // Fonte: tabela já carregada no Power Query
					    //Fonte = #"Materiais Aplicados & Retirados",
					
					    // Captura das datas mínima e máxima
					    //DataMin = List.Min(Fonte[Data Aplicação]),
					    //DataMax = List.Max(Fonte[Data Aplicação]),
					    DataMin = #date(1969, 1, 1),
					    //DataMax = #date(2030, 1, 1), 
						DataMax = DateTime.Date(DateTime.LocalNow()),
					
					    // Criação da lista de datas
					    ListaDatas = List.Dates(
					        DataMin,
					        Duration.Days(DataMax - DataMin) + 1,
					        #duration(1,0,0,0)
					    ),
					
					    // Converte lista em tabela
					    TabelaCalendario = Table.FromList(ListaDatas, Splitter.SplitByNothing(), {"Data"}),
					
					    // Adiciona colunas de atributos do calendário
					    TipoAlterado = Table.TransformColumnTypes(TabelaCalendario, {{"Data", type date}}),
					    Ano = Table.AddColumn(TipoAlterado, "Ano", each Date.Year([Data]), Int64.Type),
					    Mes = Table.AddColumn(Ano, "Mês", each Date.Month([Data]), Int64.Type),
					    NomeMes = Table.AddColumn(Mes, "Nome Mês", each Date.MonthName([Data]), type text),
					    Dia = Table.AddColumn(NomeMes, "Dia", each Date.Day([Data]), Int64.Type),
					    DiaSemana = Table.AddColumn(Dia, "Dia Semana", each Date.DayOfWeek([Data]) + 1, Int64.Type),
					    NomeDiaSemana = Table.AddColumn(DiaSemana, "Nome Dia Semana", each Date.DayOfWeekName([Data]), type text),
					    AnoMes = Table.AddColumn(NomeDiaSemana, "Ano-Mês", each Date.ToText([Data], "yyyy-MM"), type text),
					    #"Início do Mês Inserido" = Table.AddColumn(AnoMes, "Início do Mês", each Date.StartOfMonth([Data]), type date)
					in
					    #"Início do Mês Inserido"

		annotation PBI_NavigationStepName = Navegação

		annotation PBI_ResultType = Table

