table 'mvp base_clientes'
	lineageTag: 0477a203-387f-4531-a032-2d44fa351b32

	measure ContagemClientes =
			
			CALCULATE(
			    COUNTROWS('mvp base_clientes'),
			    USERELATIONSHIP(
			        'mvp base_clientes'[data_venda],
			        'dim_calendario'[Data]
			    )
			    ,
			    NOT(ISBLANK('mvp base_clientes'[data_venda])
			))
		formatString: #,0
		lineageTag: 6d6d7974-35f0-481b-a86e-9553c6251185

	measure ContagemClientesCancelados =
			
			CALCULATE(
			    COUNTROWS('mvp base_clientes'),
			    USERELATIONSHIP(
			        'mvp base_clientes'[data_cancelamento],
			        'dim_calendario'[Data]
			    ),
			    NOT ISBLANK('mvp base_clientes'[data_cancelamento])
			)
		formatString: 0
		lineageTag: 75d6995b-9e60-4379-aeba-a114392205b8

	measure ContagemClientesAtivados =
			
			CALCULATE(
			    COUNTROWS('mvp base_clientes'),
			    USERELATIONSHIP(
			        'mvp base_clientes'[data_ativacao],
			        'dim_calendario'[Data]
			    ),
			    NOT ISBLANK('mvp base_clientes'[data_ativacao])
			)
		formatString: 0
		lineageTag: 61e11185-e9aa-4358-a3ec-223a92f403b4

	measure ContagemClientesPendentes =
			
			CALCULATE(
			    COUNTROWS('mvp base_clientes'),
			    USERELATIONSHIP(
			        'mvp base_clientes'[data_venda],
			        'dim_calendario'[Data]
			    ),
			    NOT ISBLANK('mvp base_clientes'[data_venda]),
			    'mvp base_clientes'[churn] = 0,
			    'mvp base_clientes'[ativacao] = 0,
			    'mvp base_clientes'[estagio] IN {"PRE-CONTRATO", "EM APROVAÇÃO"}
			)
		formatString: 0
		lineageTag: c66fb3bf-ee10-4465-a60b-1cf301f96e26

	column nome_cliente
		dataType: string
		lineageTag: ef3f9099-dafa-49d5-942d-3b544a47727f
		summarizeBy: none
		sourceColumn: nome_cliente

		annotation SummarizationSetBy = Automatic

	column grupo_produto
		dataType: string
		lineageTag: 09a51ff4-125e-42e0-abc4-4d978e871a0a
		summarizeBy: none
		sourceColumn: grupo_produto

		annotation SummarizationSetBy = Automatic

	column cidade
		dataType: string
		lineageTag: c97ce6da-d1a0-47dc-a29c-5dc90530c978
		summarizeBy: none
		sourceColumn: cidade

		annotation SummarizationSetBy = Automatic

	column filial_regional
		dataType: string
		lineageTag: ad66c90e-cedc-4f78-97e6-ef4d1bbfa180
		summarizeBy: none
		sourceColumn: filial_regional

		annotation SummarizationSetBy = Automatic

	column uf
		dataType: string
		lineageTag: ac6a9bed-e017-476c-a330-8f48225682b9
		summarizeBy: none
		sourceColumn: uf

		annotation SummarizationSetBy = Automatic

	column estagio
		dataType: string
		lineageTag: 0324af85-1f08-4105-8602-28c2ff4a3ba6
		summarizeBy: none
		sourceColumn: estagio

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 3de870bc-e654-43d8-a308-83f3208e72b7
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column data_venda
		dataType: dateTime
		formatString: Short Date
		lineageTag: 33095b4e-cbfb-449d-8019-1e56c9d0cd8d
		summarizeBy: none
		sourceColumn: data_venda

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column vendedor
		dataType: string
		lineageTag: 9d5eb9ac-fd66-4ae8-ace5-bfdf95f8d92c
		summarizeBy: none
		sourceColumn: vendedor

		annotation SummarizationSetBy = Automatic

	column valor_contrato
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 1c207653-9fe2-4f5c-9581-fb29a547588f
		summarizeBy: sum
		sourceColumn: valor_contrato

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column empresa
		dataType: string
		lineageTag: 28b8efac-1e71-46aa-8be3-45d692853d5c
		summarizeBy: none
		sourceColumn: empresa

		annotation SummarizationSetBy = Automatic

	column credenciado_sky
		dataType: int64
		formatString: 0
		lineageTag: 43298cbf-2108-45c0-9120-ae6426498738
		summarizeBy: sum
		sourceColumn: credenciado_sky

		annotation SummarizationSetBy = Automatic

	column possui_streaming_sky
		dataType: int64
		formatString: 0
		lineageTag: 7104245e-f20e-473b-9076-a25924fc9c8f
		summarizeBy: sum
		sourceColumn: possui_streaming_sky

		annotation SummarizationSetBy = Automatic

	column credSky
		dataType: string
		lineageTag: 33c03b8c-e125-4d72-a0c6-8f831993fbea
		summarizeBy: none
		sourceColumn: credSky

		annotation SummarizationSetBy = Automatic

	column possuiStreaming
		dataType: string
		lineageTag: c3a40d26-49cf-4377-bceb-74f0ccaef1db
		summarizeBy: none
		sourceColumn: possuiStreaming

		annotation SummarizationSetBy = Automatic

	column id_contrato
		dataType: int64
		formatString: 0
		lineageTag: 6b7fe68f-4324-4da9-a736-21ce94d24a5b
		summarizeBy: sum
		sourceColumn: id_contrato

		annotation SummarizationSetBy = Automatic

	column plano
		dataType: string
		lineageTag: 3b4ef687-832c-4879-9c05-f49d08ecb651
		summarizeBy: none
		sourceColumn: plano

		annotation SummarizationSetBy = Automatic

	column velocidade
		dataType: string
		lineageTag: f1f8148f-453d-4334-9ab9-344c728f02b8
		summarizeBy: none
		sourceColumn: velocidade

		annotation SummarizationSetBy = Automatic

	column usuario
		dataType: string
		lineageTag: a99cb7ca-67f8-4d8d-be8a-fa908c74d43f
		summarizeBy: none
		sourceColumn: usuario

		annotation SummarizationSetBy = Automatic

	column data_ativacao
		dataType: dateTime
		formatString: Short Date
		lineageTag: e0d5d571-8f1b-4fb4-ae8f-c0509e24703f
		summarizeBy: none
		sourceColumn: data_ativacao

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column data_cancelamento
		dataType: dateTime
		formatString: Short Date
		lineageTag: 25de479d-fed5-4647-8de4-f6878855a3d5
		summarizeBy: none
		sourceColumn: data_cancelamento

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ativacao
		dataType: int64
		formatString: 0
		lineageTag: e2bfded8-b963-4d40-ad0f-f1b184ae82ef
		summarizeBy: sum
		sourceColumn: ativacao

		annotation SummarizationSetBy = Automatic

	column churn
		dataType: int64
		formatString: 0
		lineageTag: 49ced495-c6c5-4054-b7c9-f6563c71e9f5
		summarizeBy: sum
		sourceColumn: churn

		annotation SummarizationSetBy = Automatic

	column mvno
		dataType: int64
		formatString: 0
		lineageTag: c37e83df-4a51-47d2-8f8b-f7cf846d0ff2
		summarizeBy: sum
		sourceColumn: mvno

		annotation SummarizationSetBy = Automatic

	column evento
		dataType: string
		lineageTag: 7e8dcdc8-7792-421c-a9e7-01d166ce2f0b
		summarizeBy: none
		sourceColumn: evento

		annotation SummarizationSetBy = Automatic

	column tecnologia
		dataType: string
		lineageTag: fab01570-f1bd-4afb-b416-aab08e90ed57
		summarizeBy: none
		sourceColumn: tecnologia

		annotation SummarizationSetBy = Automatic

	column evento_macro =
			
			
			IF(
			    CONTAINSSTRING('mvp base_clientes'[evento], "INADIMPLENTE") || CONTAINSSTRING('mvp base_clientes'[evento], "INADIMPLÊNCIA"),
			    "INVOLUNTÁRIO",
			    "VOLUNTÁRIO"
			)
		lineageTag: 11ae7541-031c-4c59-bc2e-7787bdc31808
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'mvp base_clientes' = m
		mode: import
		source =
				let
				    Fonte =
				        PostgreSQL.Database(host, database),
				
				    mvp_base_clientes =
				        Fonte{
				            [
				                Schema = "mvp",
				                Item = "base_clientes"
				            ]
				        }[Data],
				
				    // Mantém somente os clientes de vendedores credenciados SKY
				    #"Linhas Filtradas" =
				        Table.SelectRows(
				            mvp_base_clientes,
				            each [credenciado_sky] = 1
				        ),
				
				    // Remove colunas que não serão utilizadas no relatório
				    // A coluna "usuario" foi mantida como nome do vendedor
				    #"Colunas Removidas" =
				        Table.RemoveColumns(
				            #"Linhas Filtradas",
				            {
				                "id_cliente",
				                "concentrador",
				                "olt",
				                "cidade_olt",
				                "uf_olt",
				                "port_olt",
				                "slot_olt",
				                "tipo",
				                "endereco",
				                "numero",
				                "bairro",
				                "cod_ibge",
				                "descricao",
				                "segmento",
				                "id_vendedor",
				                "cpf_vendedor",
				                "tipo_pessoa",
				                "doc",
				                "dt_servico"
				            },
				            MissingField.Ignore
				        ),
				
				    // Define data_venda como a data principal
				    #"Data da Venda Ajustada" =
				        Table.TransformColumns(
				            #"Colunas Removidas",
				            {
				                {
				                    "data_venda",
				                    each if _ = null then null else Date.From(_),
				                    type date
				                }
				            }
				        ),
				
				    #"Tipos Alterados" =
				        Table.TransformColumnTypes(
				            #"Data da Venda Ajustada",
				            {
				                {"valor_contrato", Currency.Type},
				                {"credenciado_sky", Int64.Type},
				                {"possui_streaming_sky", Int64.Type},
				                {"usuario", type text}
				            }
				        ),
				
				    #"Credenciado SKY Adicionado" =
				        Table.AddColumn(
				            #"Tipos Alterados",
				            "credSky",
				            each
				                if [credenciado_sky] = 1 then "SIM"
				                else if [credenciado_sky] = 0 then "NÃO"
				                else "OUTROS",
				            type text
				        ),
				
				    #"Possui Streaming Adicionado" =
				        Table.AddColumn(
				            #"Credenciado SKY Adicionado",
				            "possuiStreaming",
				            each
				                if [possui_streaming_sky] = 1 then "SIM"
				                else if [possui_streaming_sky] = 0 then "NÃO"
				                else "OUTROS",
				            type text
				        )
				in
				    #"Possui Streaming Adicionado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

